language: python
python:
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
install:
  - pip install .
  - pip install flake8
script:
  - flake8 mockme/main.py
  - ./tests/run_cli_tests.sh
